version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    restart: always # Replaces systemd service
    environment:
      # Add any necessary environment variables here
      - DISPLAY=:0

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000" # Assuming backend runs on port 8000
    restart: always # Replaces pm2
    environment:
      # Add any necessary environment variables here
      - PYTHONUNBUFFERED=1
